### ISSUE TITLE
Директива для тестовых сборок

### ISSUE THREAD

**Issue by cher-nov** [cher-nov/Doom2D-Forever#9]
Надо бы запилить директиву TESTBUILD или как-то так, указание которой отключало бы пункт "Мультиплеер" в меню. Это позволит избежать утечек тестовых сборок новых версий с форума в будущем.

**Comment by binarymaster** [comment]
А как тогда тестировать мультиплеер? :)

**Comment by BlackDoomer** [comment]
А это уже выходит за рамки публичных тестовых сборок.

08.03.2015, 04:00, "binarymaster" <notifications@github.com>:

**Comment by binarymaster** [comment]
А, публичные тестовые. Понял.

**Comment by cher-nov** [comment]
Неактуально для данной ветви разработки.
